"""
The "before" version. Working, but everything that should be configuration
is a literal value baked into the code. Read this, run it, then go implement
the config-driven version in pipeline.py — do not edit this file.
"""
import csv
import json

INPUT_PATH = "data/v1/transactions.csv"     # hardcoded path
HIGH_VALUE_THRESHOLD = 5000                  # hardcoded business threshold
OUTPUT_PATH = "data/v1/report_hardcoded.json"  # hardcoded output location


def load_csv(path):
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        return list(reader)


def main():
    rows = load_csv(INPUT_PATH)
    n = len(rows)
    total_amount = sum(float(r["amount"]) for r in rows)
    n_fraud = sum(1 for r in rows if r["is_fraud"].lower() == "true")
    n_high_value = sum(1 for r in rows if float(r["amount"]) > HIGH_VALUE_THRESHOLD)

    report = {
        "n_transactions": n,
        "total_amount": round(total_amount, 2),
        "fraud_rate": round(n_fraud / n, 4) if n else 0.0,
        "n_high_value": n_high_value,
        "high_value_threshold": HIGH_VALUE_THRESHOLD,
    }

    with open(OUTPUT_PATH, "w") as f:
        json.dump(report, f, indent=2)

    print(f"Wrote report to {OUTPUT_PATH}")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
